create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  name text not null,
  plate text not null,
  started_at timestamptz not null default now(),
  expires_at timestamptz not null
);

create index if not exists bookings_plate_expires_at_idx
  on public.bookings (plate, expires_at);

alter table public.bookings enable row level security;
